[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Solutions for Advent of Code 2025 challenges."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pytest>=9.0.0",
]
